export const MENU = [
  {
    id: 'vgoif',
    idParent: '',
    display: 'Daftar Produk',
    name: 'produk',
    path: '/product',
    show: true,
    search: true,
    enabled: true,
    group: 'data',
    type: 'menu',
    seo: {
      title: '',
      description: 'Lihat semua produk yang tersedia di inventaris.',
    },
    privileges: ['view', 'create', 'update', 'delete'],
  },
  {
    id: 'qeuln',
    idParent: '',
    display: 'Management User',
    name: 'management-user',
    path: '/management-user',
    show: true,
    search: true,
    enabled: true,
    group: 'data',
    type: 'menu',
    seo: {
      title: '',
      description: 'Lihat semua pengguna yang terdaftar dan kelola perannya di sistem.',
    },
    privileges: ['view', 'create', 'update', 'delete'],
  },
  {
    id: 'qkcmw',
    idParent: '',
    display: 'Product List',
    name: 'product-list',
    path: '/product-list',
    show: true,
    search: true,
    enabled: true,
    group: 'data',
    type: 'menu',
    seo: {
      title: '',
      description: 'Lihat semua pengguna yang terdaftar dan kelola perannya di sistem.',
    },
    privileges: ['view'],
  },
  {
    id: 'dbmbf',
    idParent: '',
    display: 'Product List Detail',
    name: 'product-list-detail',
    path: '/product-list/detail',
    show: true,
    search: true,
    enabled: true,
    group: 'data',
    type: 'menu',
    seo: {
      title: '',
      description: 'Lihat semua pengguna yang terdaftar dan kelola perannya di sistem.',
    },
    privileges: ['view'],
  },
]
